name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore src/CloudNativeEstimationHelper/CloudNativeEstimationHelper.csproj

    - name: Build project
      run: dotnet build src/CloudNativeEstimationHelper/CloudNativeEstimationHelper.csproj --configuration Release

    - name: Publish project
      run: dotnet publish src/CloudNativeEstimationHelper/CloudNativeEstimationHelper.csproj --configuration Release --output release/wwwroot

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
          token: ${{ secrets.TOKEN_GITHUB }}

