name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      

    - name: Restore dependencies
      run: dotnet restore src/CloudNativeEstimationHelper/CloudNativeEstimationHelper.csproj

    - name: Build project
      run: dotnet build src/CloudNativeEstimationHelper/CloudNativeEstimationHelper.csproj --configuration Release

    - name: Publish project
      run: dotnet publish src/CloudNativeEstimationHelper/CloudNativeEstimationHelper.csproj --configuration Release --output release/wwwroot

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: release/wwwroot # The folder the action should deploy.

